version: "3.8"
services:
  logger:
    image: james7132/hourai:latest-logger
    build:
      context: ..
      dockerfile: crates/hourai-logger/Dockerfile
  nginx:
    image: james7132/hourai:latest-frontend
    build:
      context: ..
      dockerfile: frontend/Dockerfile
